name: Continuous Integration (test ONLY)

on:
  push:
    branches: ["*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-22.04]
        scala: [2.12, 2.13, 3]
        java: [temurin@21, temurin@8]
        exclude:
          - scala: 2.12
            java: temurin@8
          - scala: 3
            java: temurin@8
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Setup Java (temurin@21)
        id: setup-java-temurin-21
        if: matrix.java == 'temurin@21'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: sbt update
        if: matrix.java == 'temurin@21' && steps.setup-java-temurin-21.outputs.cache-hit == 'false'
        run: sbt +update

      - name: Setup Java (temurin@8)
        id: setup-java-temurin-8
        if: matrix.java == 'temurin@8'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: sbt

      - name: sbt update
        if: matrix.java == 'temurin@8' && steps.setup-java-temurin-8.outputs.cache-hit == 'false'
        run: sbt +update

      - name: Check that workflows are up to date
        run: sbt githubWorkflowCheck

      - run: sbt '++ ${{ matrix.scala }}' ci

      - if: matrix.scala == '2.13' && matrix.java == 'temurin@21'
        run: sbt '++ ${{ matrix.scala }}' docs/run
